# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99743b39e418d0870f34c2747c692113a93d5a2e901023de741315b94f63a3ed70863752c5caf0afe1282ab22f42296a317973a2d48379bb9980ece0196dcb3

test:
  secret_key_base: a08fb5c619f9823558d16cb181bc74235708f4de35a0324caf12db6e1e21ba4dc73710a6921086f69652eed66d18ed6364d6762b821ad96cfa25fae143d4c4fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
